version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      # Update bundler
      - run: gem update --system
      - run: bundle update --bundler
      - run: bundle install
      # Run the tests
      - run: bundle exec rake
