version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update bundler
          command: gem update --system
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run: bundle exec rake
